### ISSUE TITLE
Question on implementation of GTA5 experiments

### ISSUE THREAD

**Issue by changliu816** [minghchen/MaxSquareLoss#1]
Hi,

After I got the pretrained source only model, I ran the code (MaxSquareLoss) for 80000 iterations but the performance I got is 42.13 iou. 

I also tried to train the model from the scratch (not based on a pretrained source only model) while getting 42.35  iou.

Could you elaborate more about the implementation detail when source only pretrained model is available ?

Best,
Chang

**Comment by minghchen** [comment]
We have tested on our device for many times and the results are 44.1miou-44.3miou

We use the following line, mentioned in readme:
`python3 tools/solve_gta5.py --gpu "1" --backbone "deeplabv2_multi" --dataset 'cityscapes' --checkpoint_dir "./log/gta2city_AdaptSegNet_ST=0.1_maxsquare_round=5/" --pretrained_ckpt_file "./pretrained_model/GTA5_source.pth" --round_num 5 --target_mode "maxsquare" --freeze_bn False --weight_decay 5e-4 --lr 2.5e-4 --lambda_target 0.1`

It is important to use a pre-trained source model.

Make sure that you see the INFO 

> Checkpoint loaded successfully from ./pretrained_model/GTA5_source.pth
