### ISSUE TITLE
"--show_num_images" can't work in eval?

### ISSUE THREAD

**Issue by yeRuiHuan** [minghchen/MaxSquareLoss#7]
When I run the following command, and add a parameter "--show_num_images 10", the val result on tensorboard still has two sets of pictures, which is default situation. Do I need to add the parameter "--show_num_images" in training?
```
python3 tools/evaluate.py --gpu "0" --dataset 'cityscapes' --checkpoint_dir "./log/eval_city" --pretrained_ckpt_file "./log/gta2city_AdaptSegNet_ST=0.1_maxsquare_round=5/gta52city_maxsquarebest.pth" --image_summary True --flip True
```

**Comment by minghchen** [comment]
"--show_num_images" should be smaller than the batch size, and the batch size is 2.
