### ISSUE TITLE
Results are not consistent with the reported

### ISSUE THREAD

**Issue by omerlandau** [minghchen/MaxSquareLoss#8]
hello, 
i've been training the GTA5 model couple of times, even when using pretrained pth on source only, maximum miou is 43.6. using the instructions gave in this repo on the IW maximum + multi. 
how come you've managed to score above 46 training this way, this is a big gap. 
thanks in advance, omer.

**Comment by greeneggsandyaml** [comment]
Hi @omerlandau, did you manage to solve this issue? I am also having difficulty reproducing the results.
